name: Release

on:
  pull_request:
    branches:
      - main

permissions: {}

jobs:
  update-sha:
    permissions:
      contents: write
    runs-on: ubuntu-26.04
    if: startsWith(github.head_ref, 'release-')
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update checksums
        run: python3 scripts/update-checksums.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if ! git diff --exit-code Formula/earth.rb; then
            git add Formula/earth.rb
            git commit -m "chore: update sha256 checksums"
            git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
            echo "No checksum changes detected."
          fi
